### ISSUE TITLE
Update to 0.15.0.5

### ISSUE THREAD

**Issue by scottAnselmo** [monero-ecosystem/monerobox#1]
Problem: monerobox currently uses an out of date binary, 0.15.0.1 as seen in demo: http://demo.monerobox.store/

Solution: Update to use current binary, 0.15.0.5 which has been out for a month now: https://github.com/monero-project/monero/releases

**Comment by Jasonhcwong** [comment]
This is a warning message. 
Usually monero do a protocol update(hard fork) every 6 months usually every April and October. But this time they don’t have a schedule for hard fork so far. The warning message is issued about every half year. It is safe to ignore it now. 
The release of 0.16 will clear this warning message.
